attack_settings:
  default_ports: [80, 443]
  default_thread_count: 100
  attack_modes:
    - "Automatic"
    - "SYN Flood"
    - "HTTP DDoS"
    - "Stealth Probe"
    - "Custom Exploit"
  logging:
    enabled: true
    log_file: "attack_log.txt"
    log_level: "INFO"

network_settings:
  max_bandwidth_usage: "100MBps"
  packet_interval: 0.1

gui_settings:
  appearance_mode: "System"
  theme: "dark-blue"
